CC=g++

CFLAGS=-Wall

LDFLAGS=-lws2_32

SERVER=server
CLIENT=client

all: $(SERVER) $(CLIENT)

$(SERVER): server.cpp
	$(CC) $(CFLAGS) server.cpp -o $(SERVER) $(LDFLAGS)

$(CLIENT): client.cpp
	$(CC) $(CFLAGS) client.cpp -o $(CLIENT) $(LDFLAGS)

clean:
	rm -f $(SERVER) $(CLIENT)